homeassistant:
  name: Home
  latitude: 50.80
  longitude: 12.90
  elevation: 0
  unit_system: metric
  time_zone: UTC
config:
frontend:
  development_repo: /home/bs/home-assistant-polymer

history:
demo:
media_player:
  - platform: demo
weather:
  - platform: demo

sensor:
  - platform: demo
  - platform: random
    name: conductivity
  - platform: random
    name: battery
  - platform: random
    name: brightness

plant:
  Bonsai:
    sensors:
      moisture: sensor.outside_humidity
      battery: sensor.battery
      temperature: sensor.outside_temperature
      conductivity: sensor.conductivity
      brightness: sensor.brightness